### ISSUE TITLE
fstab dupes on multiple runs

### ISSUE THREAD

**Issue by ghost** [Redecorating/archinstall-mbp#11]
for example, if script errors after fstab entry and is rerun a duplicate entry is added to fstab like:

```

tmpfs /tmp tmpfs defaults,noatime,mode=1777 0 0

tmpfs /tmp tmpfs defaults,noatime,mode=1777 0 0
```

**Comment by Redecorating** [comment]
i don't think that line is added by this script, could you check if it still occurs when not using this script? (if it does, then it would be an issue with archinstall)

**Comment by ghost** [comment]
Yes, upstream issue.
